#!/usr/bin/env python3
import os
import sys

if __name__ == "__main__":

    try:
        from local_repo.cmd_bootstrap_env import custom_main as selected_main

    except ImportError:
        # Run `proto_code` from `./cmd` dir:
        cmd_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cmd")
        sys.path.append(cmd_dir)
        from proto_kernel import main as selected_main

        sys.path.pop()

    selected_main()
