#!/usr/bin/env python3
# FT_93_57_03_75.app_vs_lib.md: see also `./cmd/env_bootstrapper`

if __name__ == "__main__":

    proto_kernel_rel_path = "./proto_code/proto_kernel.py"

    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    # Boilerplate to import `proto_kernel` from `protoprimer`
    import os
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "proto_kernel",
        os.path.join(os.path.dirname(__file__), proto_kernel_rel_path),
    )
    proto_kernel = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(proto_kernel)
    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    proto_kernel.app_starter("local_doc.cmd_app_starter:custom_main")
