#!/usr/bin/env python3

if __name__ == "__main__":

    proto_kernel_rel_path = "./proto_code/proto_kernel.py"

    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    # Boilerplate to import `proto_kernel` from `protoprimer`
    import os
    import sys

    # Import `proto_kernel` from `./proto_code` dir relative to curr file:
    sys.path.append(
        os.path.join(
            os.path.dirname(__file__),
            os.path.dirname(proto_kernel_rel_path),
        ),
    )
    import proto_kernel

    sys.path.pop()
    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    proto_kernel.run_main(
        "local_repo.cmd_bootstrap_env",
        "custom_main",
    )
