#!/usr/bin/env python3

if __name__ == "__main__":

    proto_kernel_rel_path = "./proto_code/proto_kernel.py"

    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    # Boilerplate to import `proto_kernel` from `protoprimer`
    import os
    import importlib.util

    proto_kernel_abs_path = os.path.join(
        os.path.dirname(__file__),
        proto_kernel_rel_path,
    )
    module_spe = importlib.util.spec_from_file_location(
        "proto_kernel",
        proto_kernel_abs_path,
    )
    proto_kernel = importlib.util.module_from_spec(module_spe)
    module_spe.loader.exec_module(proto_kernel)
    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    proto_kernel.get_derived_config()
