#!/usr/bin/env python3
# FT_93_57_03_75.app_vs_lib.md: see also `./cmd/hello_world_via_app`

if __name__ == "__main__":

    proto_kernel_rel_path = "./proto_code/proto_kernel.py"

    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    # Boilerplate to import `proto_kernel` from `protoprimer`
    import os
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "proto_kernel",
        os.path.join(os.path.dirname(__file__), proto_kernel_rel_path),
    )
    proto_kernel = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(proto_kernel)
    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    if proto_kernel.switch_to_venv(
        # ./cmd/file -> ./
        ref_root_dir_abs_path=os.path.dirname(os.path.dirname(__file__)),
    ):
        from local_doc.cmd_hello_world_via_lib import main

        main()
