#!/usr/bin/env python3
import os

from proto_kernel import delegate_to_venv

if __name__ == "__main__":

    if not delegate_to_venv(
        # ./cmd/file -> ./
        client_dir_path=os.path.dirname(os.path.dirname(__file__)),
    ):
        from local_repo.cmd_publish_package import publish_package

        publish_package(client_dir=os.path.dirname(os.path.dirname(__file__)))
