#!/usr/bin/env python3


def import_proto_kernel(proto_kernel_rel_path):
    """
    `protoprimer` entry script boilerplate function to import `proto_kernel`.
    """
    import os
    import importlib.util

    module_spec = importlib.util.spec_from_file_location(
        "proto_kernel",
        os.path.join(
            os.path.dirname(__file__),
            proto_kernel_rel_path,
        ),
    )
    loaded_proto_kernel = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(loaded_proto_kernel)
    return loaded_proto_kernel


if __name__ == "__main__":
    proto_kernel = import_proto_kernel("./proto_code/proto_kernel.py")

    import os

    os.environ["PROTOPRIMER_DO_INSTALL"] = str(False)

    # TODO: Do we really want to start `venv_shell` as `env_bootstrapper` (not as `app_starter`)?
    proto_kernel.env_bootstrapper("neoprimer.cmd_venv_shell:custom_main")
