run-name: "${{ github.workflow }}: ${{ github.actor }}: ${{ github.event_name }}: ${{ github.ref_name }}: ${{ github.ref_type }}"
on:
    push:
        branches:
        -   "*"
jobs:
    bootstrap_scenarios:
        runs-on: ubuntu-latest

        steps:
            -   run: "echo runner.os: ${{ runner.os }}"
            -   run: "echo github.repository: ${{ github.repository }}"
            -   run: "echo github.ref: ${{ github.ref }}"

            -   uses: actions/setup-python@v5
                with:
                    # FT_84_11_73_28: supported python versions:
                    python-version: 3.14

            -   run: "python -c \"import sys; print(sys.version);\""

            -   uses: actions/checkout@v4

            -   run: "${{ github.workspace }}/prime"
            -   run: "${{ github.workspace }}/cmd/bootstrap_env"

            -   name: ensure git has no local changes and untracked files
                run: |
                    git diff || true
                    git status --porcelain || true
                    test -z "$(git status --porcelain)"

            # TODO: At the moment, we do not render docs, for now just check that `gen_next_doc_id` works:
            -   run: "${{ github.workspace }}/cmd/gen_next_doc_id ${{ github.workspace }}/doc/feature_topic"
            -   run: "${{ github.workspace }}/cmd/gen_next_doc_id ${{ github.workspace }}/doc/use_case"
            -   run: "${{ github.workspace }}/cmd/gen_next_doc_id ${{ github.workspace }}/doc/task_ref"

            -   run: "echo job.status: ${{ job.status }}"
