run-name: "${{ github.workflow }}: ${{ github.actor }}: ${{ github.event_name }}: ${{ github.ref_name }}: ${{ github.ref_type }}"
on:
    push:
        branches:
        -   "*"
    pull_request:
        branches:
        -   "*"
jobs:
    bootstrap_scenarios:
        runs-on: ubuntu-latest

        steps:
            -   run: "echo runner.os: ${{ runner.os }}"
            -   run: "echo github.repository: ${{ github.repository }}"
            -   run: "echo github.ref: ${{ github.ref }}"

            -   uses: actions/setup-python@v5
                with:
                    # FS_84_11_73_28: supported python versions:
                    python-version: 3.13

            -   run: "python -c \"import sys; print(sys.version);\""

            -   uses: actions/checkout@v4

            -   run: "${{ github.workspace }}/cmd/bootstrap_env"

            -   name: generate coverage for `protoprimer` distrib package
                run: "${{ github.workspace }}/venv/bin/coverage run --branch --source=${{ github.workspace }}/src/protoprimer/main/ --module unittest discover --start-directory ${{ github.workspace }}/src/protoprimer/test/"

            -   name: report coverage
                run: "${{ github.workspace }}/venv/bin/coverage report --show-missing --no-skip-covered"

            -   name: convert coverage
                run: "${{ github.workspace }}/venv/bin/coverage xml"

            -   name: coveralls.io
                env:
                    COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
                uses: coverallsapp/github-action@v2

            -   run: "echo job.status: ${{ job.status }}"
