run-name: "${{ github.workflow }}: ${{ github.actor }}: ${{ github.event_name }}: ${{ github.ref_name }}: ${{ github.ref_type }}"
on:
    push:
        branches:
        -   "*"
jobs:
    bootstrap_scenarios:
        runs-on: ubuntu-latest

        steps:
            -   run: "echo runner.os: ${{ runner.os }}"
            -   run: "echo github.repository: ${{ github.repository }}"
            -   run: "echo github.ref: ${{ github.ref }}"

            -   uses: actions/setup-python@v5
                with:
                    # FS_84_11_73_28: supported python versions:
                    python-version: 3.13

            -   run: "python -c \"import sys; print(sys.version);\""

            -   uses: actions/checkout@v4

            -   run: "${{ github.workspace }}/cmd/bootstrap_env dst_conf_env/default_env/"

            -   run: "${{ github.workspace }}/venv/bin/python -m unittest discover --start-directory ${{ github.workspace }}/src/test/"

            -   name: ensure git has no local changes and untracked files
                run: "test -z \"$(git status --porcelain)\""

            -   run: "echo job.status: ${{ job.status }}"
