run-name: "${{ github.workflow }}: ${{ github.actor }}: ${{ github.event_name }}: ${{ github.ref_name }}: ${{ github.ref_type }}"
on:
    push:
        branches:
        -   "*"
    schedule:
        # Keep running periodically to detect issues with newly released dependencies:
        # Every day at 18:00 SGT:
        -   cron: "0 10 * * *"
jobs:
    bootstrap_scenarios:
        runs-on: ubuntu-latest

        strategy:
            # When one of the jobs fails, this prevents canceling another job (for another Python version):
            fail-fast: false
            matrix:
                # FS_84_11_73_28: supported python versions:
                python-version:
                    -   3.8
                    -   3.13
        steps:
            -   run: "echo runner.os: ${{ runner.os }}"
            -   run: "echo github.repository: ${{ github.repository }}"
            -   run: "echo github.ref: ${{ github.ref }}"

            -   name: "matrix.python-version: ${{ matrix.python-version }}"
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ matrix.python-version }}

            -   run: "python -c \"import sys; print(sys.version);\""

            -   uses: actions/checkout@v4

            -   run: "${{ github.workspace }}/cmd/bootstrap_env"

            -   run: "${{ github.workspace }}/venv/bin/python -m unittest discover --start-directory ${{ github.workspace }}/src/protoprimer/test/"
            -   run: "${{ github.workspace }}/venv/bin/python -m unittest discover --start-directory ${{ github.workspace }}/src/local_repo/test/"
            -   run: "${{ github.workspace }}/venv/bin/python -m unittest discover --start-directory ${{ github.workspace }}/src/local_test/test/"

            -   run: "echo job.status: ${{ job.status }}"
